-- INSERT INTO categories (name)
-- VALUES ('Смартфоны');
-- INSERT INTO categories (name)
-- VALUES ('Планшеты');
-- INSERT INTO categories (name)
-- VALUES ('Телевизоры');
-- INSERT INTO categories (name)
-- VALUES ('Аксессуары');